<a href="https://colab.research.google.com/github/tryingtolearn11/CS44800/blob/main/a3/a3_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


In [106]:
# Imports section
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline

## Part 1. Loading the dataset

In [107]:
# Using pandas load the dataset (load remotely, not locally)
# Output the first 15 rows of the data
# Display a summary of the table information (number of datapoints, etc.)
data = pd.read_csv("https://raw.githubusercontent.com/profmcnich/example_notebook/main/science_data_large.csv")
data.head(15)

Temperature °C  Mols KCL     Size nm^3
0              469       647  6.244743e+05
1              403       694  5.779610e+05
2              302       975  6.196847e+05
3              779       916  1.460449e+06
4              901        18  4.325726e+04
5              545       637  7.124634e+05
6              660       519  7.006960e+05
7              143       869  2.718260e+05
8               89       461  8.919803e+04
9              294       776  4.770210e+05
10             991       117  2.441771e+05
11             307       781  5.006455e+05
12             206        70  3.145200e+04
13             437       599  5.390215e+05
14             566        75  9.185271e+04

In [108]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Temperature °C  1000 non-null   int64  
 1   Mols KCL        1000 non-null   int64  
 2   Size nm^3       1000 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 23.6 KB


## Part 2. Splitting the dataset

In [109]:
# Take the pandas dataset and split it into our features (X) and label (y)
# X : Temperature and Mols KCL
# Y : Size of the Slime
x = data[["Temperature °C", "Mols KCL"]]
y = data["Size nm^3"]

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, train_size=0.9)

## Part 3. Perform a Linear Regression

In [110]:
# Use sklearn to train a model on the training set
reg = LinearRegression().fit(x_train.values, y_train)

# Create a sample datapoint and predict the output of that sample with the trained model
sample_datapoint = np.array([[290, 582]])
reg.predict(sample_datapoint)

array([444366.35368926])

In [111]:
# Report on the score for that model, in your own words (markdown, not code) explain what the score means
reg.score(x_train.values, y_train)

0.8653649719524311

#### Score=```0.861994```
This score is an evaluation of how accurate the model is based on our training data. Generally a model with a score closer to 1.0 is considered more accurate. For this model in particular, we consider ```~86%``` to be fairly good but there is certainly room for improvement.

In [112]:
# Extract the coefficents and intercept from the model and write an equation for your h(x) using LaTeX
reg.coef_

array([ 872.72567248, 1045.52592373])

In [113]:
reg.intercept_

-417220.178938936

### $h (x)$ =   $\theta$<sub>1</sub>$x$ + $\theta$<sub>0</sub>
##### Note: We have two coefficents here, so we will have  $x$<sub>1</sub> and $x$<sub>2</sub>

### $h (x)$ = $882.06908216$ $x$<sub>1</sub> $+$ $1021.78993405$ $x$<sub>2</sub> $-$ $417063.34541090037$


Sample equation: $E = mc^2$

## Part 4. Use Cross Validation

In [114]:
# Use the cross_val_score function to repeat your experiment across many shuffles of the data
scores = cross_val_score(reg, x, y, cv=5)
# Report on their finding and their significance 
scores

array([0.83918826, 0.87051239, 0.85871066, 0.87202623, 0.84364641])

In [115]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.86 accuracy with a standard deviation of 0.01


#### ```0.86``` Accuracy 
Here we can see that after cross validating, we maintain a consistent score of ~ ```0.86```. This supports our original score from Part three. Note that the STD is ```0.01``` which means that the model appears to be stable and certainly more reputable.

## Part 5. Using Polynomial Regression

In [116]:
# Using the PolynomialFeatures library perform another regression on an augmented dataset of degree 2
poly = PolynomialFeatures(degree=2)
poly.fit_transform(x)

array([[1.00000e+00, 4.69000e+02, 6.47000e+02, 2.19961e+05, 3.03443e+05,
        4.18609e+05],
       [1.00000e+00, 4.03000e+02, 6.94000e+02, 1.62409e+05, 2.79682e+05,
        4.81636e+05],
       [1.00000e+00, 3.02000e+02, 9.75000e+02, 9.12040e+04, 2.94450e+05,
        9.50625e+05],
       ...,
       [1.00000e+00, 7.91000e+02, 2.13000e+02, 6.25681e+05, 1.68483e+05,
        4.53690e+04],
       [1.00000e+00, 7.69000e+02, 5.53000e+02, 5.91361e+05, 4.25257e+05,
        3.05809e+05],
       [1.00000e+00, 9.19000e+02, 4.52000e+02, 8.44561e+05, 4.15388e+05,
        2.04304e+05]])

In [117]:
# Report on the metrics and output the resultant equation as you did in Part 3.
model = Pipeline([('poly', PolynomialFeatures(degree=2)),
                  ('linear', LinearRegression(fit_intercept=False))])

model = model.fit(x_train.values, y_train)
model.named_steps['linear'].coef_


array([ 2.01837598e-05,  1.20000000e+01, -1.51861656e-07, -2.14672724e-11,
        2.00000000e+00,  2.85714287e-02])

Now after re-labeling the data, we have: $z$ $=$ $[2.06638424e-05, 1.20000000e+01, -1.23656469e-07, 1.87814209e-11, 2.00000000e+00, 2.85714287e-02]$
